// Countries list (code → name) — matches Stripe checkout values
const COUNTRIES_LIST = [
  { code: "AF", name: "Afghanistan" },{ code: "AL", name: "Albania" },{ code: "DZ", name: "Algeria" },
  { code: "AD", name: "Andorra" },{ code: "AO", name: "Angola" },{ code: "AG", name: "Antigua & Barbuda" },
  { code: "AR", name: "Argentina" },{ code: "AM", name: "Armenia" },{ code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },{ code: "AZ", name: "Azerbaijan" },{ code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },{ code: "BD", name: "Bangladesh" },{ code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },{ code: "BE", name: "Belgium" },{ code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },{ code: "BT", name: "Bhutan" },{ code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia & Herzegovina" },{ code: "BW", name: "Botswana" },{ code: "BR", name: "Brazil" },
  { code: "BN", name: "Brunei" },{ code: "BG", name: "Bulgaria" },{ code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },{ code: "CA", name: "Canada" },{ code: "CL", name: "Chile" },
  { code: "CN", name: "China" },{ code: "CO", name: "Colombia" },{ code: "CR", name: "Costa Rica" },
  { code: "HR", name: "Croatia" },{ code: "CY", name: "Cyprus" },{ code: "CZ", name: "Czech Republic" },
  { code: "DK", name: "Denmark" },{ code: "DO", name: "Dominican Republic" },{ code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },{ code: "SV", name: "El Salvador" },{ code: "EE", name: "Estonia" },
  { code: "ET", name: "Ethiopia" },{ code: "FI", name: "Finland" },{ code: "FR", name: "France" },
  { code: "GA", name: "Gabon" },{ code: "GE", name: "Georgia" },{ code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },{ code: "GR", name: "Greece" },{ code: "GT", name: "Guatemala" },
  { code: "GY", name: "Guyana" },{ code: "HN", name: "Honduras" },{ code: "HK", name: "Hong Kong" },
  { code: "HU", name: "Hungary" },{ code: "IS", name: "Iceland" },{ code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },{ code: "IQ", name: "Iraq" },{ code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" },{ code: "IT", name: "Italy" },{ code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },{ code: "JO", name: "Jordan" },{ code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },{ code: "KW", name: "Kuwait" },{ code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },{ code: "LT", name: "Lithuania" },{ code: "LU", name: "Luxembourg" },
  { code: "MO", name: "Macau" },{ code: "MY", name: "Malaysia" },{ code: "MT", name: "Malta" },
  { code: "MX", name: "Mexico" },{ code: "MD", name: "Moldova" },{ code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },{ code: "ME", name: "Montenegro" },{ code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },{ code: "MM", name: "Myanmar" },{ code: "NA", name: "Namibia" },
  { code: "NP", name: "Nepal" },{ code: "NL", name: "Netherlands" },{ code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },{ code: "NG", name: "Nigeria" },{ code: "MK", name: "North Macedonia" },
  { code: "NO", name: "Norway" },{ code: "OM", name: "Oman" },{ code: "PK", name: "Pakistan" },
  { code: "PA", name: "Panama" },{ code: "PY", name: "Paraguay" },{ code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },{ code: "PL", name: "Poland" },{ code: "PT", name: "Portugal" },
  { code: "QA", name: "Qatar" },{ code: "RO", name: "Romania" },{ code: "RU", name: "Russia" },
  { code: "RW", name: "Rwanda" },{ code: "SA", name: "Saudi Arabia" },{ code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },{ code: "SG", name: "Singapore" },{ code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },{ code: "ZA", name: "South Africa" },{ code: "KR", name: "South Korea" },
  { code: "ES", name: "Spain" },{ code: "LK", name: "Sri Lanka" },{ code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },{ code: "TW", name: "Taiwan" },{ code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },{ code: "TT", name: "Trinidad & Tobago" },{ code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },{ code: "UG", name: "Uganda" },{ code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },{ code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },{ code: "UY", name: "Uruguay" },{ code: "UZ", name: "Uzbekistan" },
  { code: "VE", name: "Venezuela" },{ code: "VN", name: "Vietnam" },{ code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
];

// States/provinces by country code
const STATES = {
  US: [
    { code: "AL", name: "Alabama" },{ code: "AK", name: "Alaska" },{ code: "AZ", name: "Arizona" },
    { code: "AR", name: "Arkansas" },{ code: "CA", name: "California" },{ code: "CO", name: "Colorado" },
    { code: "CT", name: "Connecticut" },{ code: "DE", name: "Delaware" },{ code: "DC", name: "District of Columbia" },
    { code: "FL", name: "Florida" },{ code: "GA", name: "Georgia" },{ code: "HI", name: "Hawaii" },
    { code: "ID", name: "Idaho" },{ code: "IL", name: "Illinois" },{ code: "IN", name: "Indiana" },
    { code: "IA", name: "Iowa" },{ code: "KS", name: "Kansas" },{ code: "KY", name: "Kentucky" },
    { code: "LA", name: "Louisiana" },{ code: "ME", name: "Maine" },{ code: "MD", name: "Maryland" },
    { code: "MA", name: "Massachusetts" },{ code: "MI", name: "Michigan" },{ code: "MN", name: "Minnesota" },
    { code: "MS", name: "Mississippi" },{ code: "MO", name: "Missouri" },{ code: "MT", name: "Montana" },
    { code: "NE", name: "Nebraska" },{ code: "NV", name: "Nevada" },{ code: "NH", name: "New Hampshire" },
    { code: "NJ", name: "New Jersey" },{ code: "NM", name: "New Mexico" },{ code: "NY", name: "New York" },
    { code: "NC", name: "North Carolina" },{ code: "ND", name: "North Dakota" },{ code: "OH", name: "Ohio" },
    { code: "OK", name: "Oklahoma" },{ code: "OR", name: "Oregon" },{ code: "PA", name: "Pennsylvania" },
    { code: "RI", name: "Rhode Island" },{ code: "SC", name: "South Carolina" },{ code: "SD", name: "South Dakota" },
    { code: "TN", name: "Tennessee" },{ code: "TX", name: "Texas" },{ code: "UT", name: "Utah" },
    { code: "VT", name: "Vermont" },{ code: "VA", name: "Virginia" },{ code: "WA", name: "Washington" },
    { code: "WV", name: "West Virginia" },{ code: "WI", name: "Wisconsin" },{ code: "WY", name: "Wyoming" },
  ],
  CA: [
    { code: "AB", name: "Alberta" },{ code: "BC", name: "British Columbia" },{ code: "MB", name: "Manitoba" },
    { code: "NB", name: "New Brunswick" },{ code: "NL", name: "Newfoundland and Labrador" },
    { code: "NS", name: "Nova Scotia" },{ code: "NT", name: "Northwest Territories" },
    { code: "NU", name: "Nunavut" },{ code: "ON", name: "Ontario" },{ code: "PE", name: "Prince Edward Island" },
    { code: "QC", name: "Quebec" },{ code: "SK", name: "Saskatchewan" },{ code: "YT", name: "Yukon" },
  ],
  AU: [
    { code: "ACT", name: "Australian Capital Territory" },{ code: "NSW", name: "New South Wales" },
    { code: "NT", name: "Northern Territory" },{ code: "QLD", name: "Queensland" },
    { code: "SA", name: "South Australia" },{ code: "TAS", name: "Tasmania" },
    { code: "VIC", name: "Victoria" },{ code: "WA", name: "Western Australia" },
  ],
  IN: [
    { code: "AN", name: "Andaman & Nicobar Islands" },{ code: "AP", name: "Andhra Pradesh" },
    { code: "AR", name: "Arunachal Pradesh" },{ code: "AS", name: "Assam" },{ code: "BR", name: "Bihar" },
    { code: "CG", name: "Chhattisgarh" },{ code: "DL", name: "Delhi" },{ code: "GA", name: "Goa" },
    { code: "GJ", name: "Gujarat" },{ code: "HR", name: "Haryana" },{ code: "HP", name: "Himachal Pradesh" },
    { code: "JK", name: "Jammu & Kashmir" },{ code: "JH", name: "Jharkhand" },{ code: "KA", name: "Karnataka" },
    { code: "KL", name: "Kerala" },{ code: "MP", name: "Madhya Pradesh" },{ code: "MH", name: "Maharashtra" },
    { code: "MN", name: "Manipur" },{ code: "ML", name: "Meghalaya" },{ code: "MZ", name: "Mizoram" },
    { code: "NL", name: "Nagaland" },{ code: "OD", name: "Odisha" },{ code: "PB", name: "Punjab" },
    { code: "RJ", name: "Rajasthan" },{ code: "SK", name: "Sikkim" },{ code: "TN", name: "Tamil Nadu" },
    { code: "TS", name: "Telangana" },{ code: "TR", name: "Tripura" },{ code: "UP", name: "Uttar Pradesh" },
    { code: "UK", name: "Uttarakhand" },{ code: "WB", name: "West Bengal" },
  ],
};

module.exports = { COUNTRIES_LIST, STATES };
